version: '3.7'

services:
    caddy:
        image: caddy:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "81:81"
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - $PWD/build/:/srv
            - caddy_data:/data
            - caddy_config:/config

volumes:
    caddy_data:
    caddy_config:
